/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_16010b6f (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/lmkthofnydxxgowryjcz/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// Reuse single client instance instead of creating new one each time
const supabaseClient = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
    db: {
      schema: 'public',
    },
    global: {
      headers: {
        'Connection': 'keep-alive',
      },
    },
  }
);

// Helper to add timeout to operations
async function withTimeout<T>(promise: Promise<T>, timeoutMs = 30000): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error(`Database query timed out after ${timeoutMs}ms`)), timeoutMs)
    )
  ]);
}

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const { error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").upsert({
      key,
      value
    }),
    15000 // Increased from 5000ms to handle cold starts
  );
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const { data, error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").select("value").eq("key", key).maybeSingle(),
    15000 // Increased from 5000ms to handle cold starts
  );
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const { error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").delete().eq("key", key),
    15000 // Increased from 5000ms to handle cold starts
  );
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const { error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").upsert(keys.map((k, i) => ({ key: k, value: values[i] }))),
    20000 // Increased from 10000ms for batch operations
  );
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const { data, error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").select("value").in("key", keys),
    20000 // Increased from 10000ms for batch operations
  );
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const { error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").delete().in("key", keys),
    20000 // Increased from 10000ms for batch operations
  );
  if (error) {
    throw new Error(error.message);
  }
};

// PostgREST caps each response at 1000 rows by default. Without pagination, prefix scans
// silently drop newer keys (e.g. recent orders), which makes order history look empty.
const PREFIX_PAGE_SIZE = 1000;

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const allValues: any[] = [];
  let offset = 0;

  for (;;) {
    const { data, error } = await withTimeout(
      supabaseClient
        .from("kv_store_16010b6f")
        .select("key, value")
        .like("key", prefix + "%")
        .order("key", { ascending: true })
        .range(offset, offset + PREFIX_PAGE_SIZE - 1),
      30000
    );
    if (error) {
      throw new Error(error.message);
    }
    const rows = data ?? [];
    for (const row of rows) {
      allValues.push(row.value);
    }
    if (rows.length < PREFIX_PAGE_SIZE) {
      break;
    }
    offset += PREFIX_PAGE_SIZE;
  }

  return allValues;
};