// Language Context - Bilingual support
// Force recompile: 2026-02-15-fix-provider-error-v2
import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Settings Page
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your store preferences and configuration',
    'settings.general': 'General',
    'settings.users': 'Users',
    'settings.appearance': 'Appearance',
    
    // General Tab
    'settings.general.storeInfo': 'Store information',
    'settings.general.storeName': 'Store name',
    'settings.general.contactEmail': 'Contact email',
    'settings.general.contactEmailHint': 'Customers will use this email to contact you',
    'settings.general.phoneNumber': 'Phone number',
    'settings.general.storeAddress': 'Store address',
    'settings.general.regionalSettings': 'Regional settings',
    'settings.general.currency': 'Currency',
    'settings.general.timezone': 'Timezone',
    'settings.general.language': 'Language',
    'settings.general.languageHint': 'Select your preferred language for the interface',
    'settings.general.saveChanges': 'Save changes',

    // Currency & timezone (Settings selects)
    'currency.MMK': 'Myanmar Kyat (MMK)',
    'currency.CNY': 'Chinese Yuan (CNY)',
    'currency.USD': 'US Dollar (USD)',
    'timezone.America/New_York': 'Eastern Time (New York)',
    'timezone.America/Chicago': 'Central Time (Chicago)',
    'timezone.America/Denver': 'Mountain Time (Denver)',
    'timezone.America/Los_Angeles': 'Pacific Time (Los Angeles)',
    'timezone.Europe/London': 'London',
    'timezone.Asia/Tokyo': 'Tokyo',
    'timezone.Asia/Yangon': 'Yangon',
    
    // Language Options
    'language.english': 'English',
    'language.chinese': '简体中文 (Simplified Chinese)',
    
    // Users Tab
    'settings.users.totalUsers': 'total users',
    'settings.users.active': 'active',
    'settings.users.addUser': 'Add user',
    'settings.users.user': 'User',
    'settings.users.role': 'Role',
    'settings.users.status': 'Status',
    'settings.users.lastActive': 'Last active',
    'settings.users.active.status': 'Active',
    'settings.users.inactive.status': 'Inactive',
    'settings.users.viewProfile': 'View profile',
    'settings.users.editUser': 'Edit user',
    'settings.users.deleteUser': 'Delete user',
    'settings.users.deleteConfirm': 'Are you sure you want to delete this user?',
    
    // User Dialog
    'settings.users.dialog.add.title': 'Add new user',
    'settings.users.dialog.add.description': 'Create a new user account with role and permissions.',
    'settings.users.dialog.edit.title': 'Edit user',
    'settings.users.dialog.edit.description': 'Update the user information and role.',
    'settings.users.dialog.fullName': 'Full name',
    'settings.users.dialog.fullNamePlaceholder': 'e.g., John Doe',
    'settings.users.dialog.email': 'Email address',
    'settings.users.dialog.emailPlaceholder': 'john@example.com',
    'settings.users.dialog.emailHint': 'User will receive login credentials at this email',
    'settings.users.dialog.role': 'Role',
    'settings.users.dialog.avatar': 'Avatar',
    'settings.users.dialog.cancel': 'Cancel',
    'settings.users.dialog.save': 'Save changes',
    'settings.users.dialog.add': 'Add user',
    
    // Roles
    'role.storeOwner': 'Store Owner',
    'role.storeOwner.desc': 'Business owner with full store access and control',
    'role.storeOwner.full': 'Store Owner - Full access',
    'role.administrator': 'Administrator',
    'role.administrator.desc': 'Manage products, orders, and users (except owner settings)',
    'role.administrator.full': 'Administrator - Manage operations',
    'role.dataEntry': 'Data Entry',
    'role.dataEntry.desc': 'Add and edit products, manage inventory only',
    'role.dataEntry.full': 'Data Entry - Limited access',
    'role.developer': 'Developer',
    'role.developer.desc': 'Technical access for integrations and customizations',
    'role.developer.full': 'Developer - Technical access',
    'role.productManager': 'Product Manager',
    'role.productManager.desc': 'Define and manage product strategy and roadmap',
    'role.productManager.full': 'Product Manager - Strategy and roadmap',
    
    // Role Permissions
    'settings.users.rolePermissions': 'Role permissions',
    'role.storeOwner.permissions': 'Business owner with full store access and control including:',
    'role.storeOwner.perm1': 'Manage all products, orders, and content',
    'role.storeOwner.perm2': 'Access to all financial data and reports',
    'role.storeOwner.perm3': 'Add, edit, and remove users',
    'role.storeOwner.perm4': 'Modify store settings and configurations',
    'role.storeOwner.perm5': 'Cannot be deleted or deactivated',
    'role.administrator.permissions': 'Manage day-to-day operations including:',
    'role.administrator.perm1': 'Manage products, categories, and inventory',
    'role.administrator.perm2': 'Process and manage orders',
    'role.administrator.perm3': 'Access marketing and blog features',
    'role.administrator.perm4': 'View reports and analytics',
    'role.administrator.perm5': 'Cannot access owner settings or financial data',
    'role.dataEntry.permissions': 'Limited access for data management:',
    'role.dataEntry.perm1': 'Add and edit products',
    'role.dataEntry.perm2': 'Manage inventory levels',
    'role.dataEntry.perm3': 'Update product information',
    'role.dataEntry.perm4': 'Cannot delete products or access orders',
    'role.dataEntry.perm5': 'No access to settings, users, or financial data',
    'role.developer.permissions': 'Technical access for integrations and customizations:',
    'role.developer.perm1': 'Access to API documentation and tools',
    'role.developer.perm2': 'Implement custom features and integrations',
    'role.developer.perm3': 'Debug and troubleshoot technical issues',
    'role.developer.perm4': 'No access to user data or financial information',
    'role.productManager.permissions': 'Define and manage product strategy and roadmap:',
    'role.productManager.perm1': 'Develop product vision and goals',
    'role.productManager.perm2': 'Plan and prioritize product features',
    'role.productManager.perm3': 'Collaborate with development and marketing teams',
    'role.productManager.perm4': 'Monitor product performance and feedback',
    'role.productManager.perm5': 'No access to user data or financial information',
    
    // Appearance Tab
    'settings.appearance.theme': 'Theme',
    'settings.appearance.theme.light': 'Light',
    'settings.appearance.theme.dark': 'Dark',
    'settings.appearance.theme.auto': 'Auto',
    'settings.appearance.accentColor': 'Accent color',
    'settings.appearance.save': 'Save appearance',
    
    // Common
    'common.save': 'Save',
    'common.all': 'All',
    
    // Navigation
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.product': 'Product',
    'nav.orders': 'Orders',
    'nav.vendor': 'Vendor',
    'nav.collaborator': 'Collaborator',
    'nav.discount': 'Discount',
    'nav.promoSetting': 'Promo Setting',
    'nav.marketing': 'Marketing',
    'nav.liveStream': 'Live stream',
    'nav.chat': 'Chat',
    'nav.customers': 'Customers',
    'nav.finances': 'Finances',
    'nav.logistics': 'Logistics',
    'nav.blogPost': 'Blog post',
    'nav.settings': 'Settings',
    'nav.categories': 'Categories',
    'nav.inventory': 'Inventory',
    'nav.blogCategory': 'Blog category',
    
    // Footer
    'footer.createdBy': 'Created by',
    'footer.role': 'Software Architect',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back, {name}! Here\'s what\'s happening today.',
    'dashboard.viewReports': 'View Reports',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.orders': 'Orders',
    'dashboard.customers': 'Customers',
    'dashboard.products': 'Products',
    'dashboard.fromLastMonth': 'from last month',
    'dashboard.salesOverview': 'Sales Overview',
    'dashboard.salesOverviewDesc': 'Monthly sales and orders trend',
    'dashboard.topProducts': 'Top Products',
    'dashboard.topProductsDesc': 'Best performing products this month',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.latestOrders': 'Latest customer orders',
    'dashboard.viewAll': 'View All',
    'dashboard.sales': 'sales',
    'dashboard.ordersLower': 'orders',
    'dashboard.orderId': 'Order ID',
    'dashboard.customer': 'Customer',
    'dashboard.product': 'Product',
    'dashboard.amount': 'Amount',
    'dashboard.status': 'Status',
    
    // Products
    'products.title': 'Products',
    'products.subtitle': 'Manage your product inventory and details',
    'products.addProduct': 'Add Product',
    'products.allProducts': 'All Products',
    'products.vendor': 'Vendor',
    'products.collaborator': 'Collaborator',
    'products.salesVolume': 'Sales Volume',
    'products.searchPlaceholder': 'Search products by name or SKU...',
    'products.allStatus': 'All Status',
    'products.active': 'Active',
    'products.offShelf': 'Off Shelf',
    'products.newestFirst': 'Newest First',
    'products.oldestFirst': 'Oldest First',
    'products.sortByDate': 'Sort by date',
    'products.inventory': 'Inventory',
    'products.category': 'Category',
    'products.price': 'Price',
    'products.actions': 'Actions',
    'products.status': 'Status',
    
    // Add Product
    'addProduct.back': 'Back',
    'addProduct.title': 'Add product',
    'addProduct.cancel': 'Cancel',
    'addProduct.save': 'Save',
    'addProduct.productTitle': 'Title',
    'addProduct.description': 'Description',
    'addProduct.descriptionPlaceholder': 'Describe your product in detail...',
    'addProduct.productStatus': 'Product status',
    'addProduct.productOrganization': 'Product organization',
    'addProduct.productType': 'Product type',
    'addProduct.productTypePlaceholder': 'e.g., Shirts',
    'addProduct.categoryLabel': 'Category',
    'addProduct.categoryPlaceholder': 'Loading categories...',
    'addProduct.selectCategory': 'Select category',
    'addProduct.vendorLabel': 'Vendor',
    'addProduct.vendorPlaceholder': 'Select vendor',
    'addProduct.collaboratorLabel': 'Collaborator',
    'addProduct.collaboratorPlaceholder': 'Select collaborator',
    'addProduct.tags': 'Tags',
    'addProduct.tagsHint': 'Add tags to help organize and find products',
    'addProduct.enterTag': 'Enter tag...',
    'addProduct.add': 'Add',
    'addProduct.media': 'Media',
    'addProduct.uploadTip': 'Tip: Paste, drag & drop, or click to add images',
    'addProduct.detailsHint': 'Add product details, care instructions, and sizing information',
    
    // Inventory
    'inventory.title': 'Inventory',
    'inventory.totalQuantity': 'Total quantity',
    'inventory.committedQuantity': 'Committed quantity',
    'inventory.availableQuantity': 'Available quantity',
    'inventory.searchPlaceholder': 'Search inventory',
    'inventory.allStock': 'All stock',
    'inventory.export': 'Export',
    'inventory.product': 'PRODUCT',
    'inventory.sku': 'SKU',
    'inventory.available': 'AVAILABLE',
    'inventory.committed': 'COMMITTED',
    'inventory.onHand': 'ON HAND',
    'inventory.location': 'LOCATION',
    'inventory.actions': 'ACTIONS',
    
    // Categories
    'categories.title': 'Categories',
    'categories.searchPlaceholder': 'Search categories',
    'categories.deleteTestData': 'Delete Test Data',
    'categories.deleteAll': 'Delete All',
    'categories.addCategory': 'Add category',
    'categories.category': 'CATEGORY',
    'categories.description': 'DESCRIPTION',
    'categories.products': 'PRODUCTS',
    'categories.status': 'STATUS',
    'categories.actions': 'ACTIONS',
    'categories.active': 'Active',
    'categories.hidden': 'Hidden',
    'categories.backToCategories': 'Back to Categories',
    'categories.createNew': 'Create New Category',
    'categories.createSubtitle': 'Add a new category and assign products to organize your inventory',
    'categories.basicInfo': 'Basic Information',
    'categories.categoryName': 'Category Name',
    'categories.categoryNamePlaceholder': 'e.g., Electronics, Clothing, Home & Garden',
    'categories.descriptionLabel': 'Description',
    'categories.descriptionPlaceholder': 'Describe what products belong in this category...',
    'categories.categorySettings': 'Category Settings',
    'categories.statusLabel': 'Status',
    'categories.statusActive': 'Active - Visible to customers',
    'categories.coverPhoto': 'Cover Photo',
    'categories.uploadText': 'Click to upload or drag and drop',
    'categories.uploadHint': 'PNG, JPG, GIF up to 5MB',
    'categories.createButton': 'Create Category',
    'categories.cancelButton': 'Cancel',
    
    // Orders
    'orders.title': 'Orders',
    'orders.subtitle': 'Manage and track all your orders',
    'orders.loading': 'Loading...',
    'orders.totalRevenue': 'Total Revenue',
    'orders.pending': 'Pending',
    'orders.needsAttention': 'Needs attention',
    'orders.processing': 'Processing',
    'orders.inProgress': 'In progress',
    'orders.fulfilled': 'Fulfilled',
    'orders.completed': 'Completed',
    'orders.ordersTab': 'Orders',
    'orders.analyticsTab': 'Analytics',
    'orders.allOrders': 'All Orders',
    'orders.export': 'Export',
    'orders.searchPlaceholder': 'Search orders...',
    'orders.newestFirst': 'Newest First',
    'orders.oldestFirst': 'Oldest First',
    'orders.allStatus': 'All Status',
    'orders.allPayment': 'All Payment',
    'orders.allVendors': 'All Vendors',
    'orders.from': 'From',
    'orders.to': 'To',
    'orders.order': 'Order',
    'orders.date': 'Date',
    'orders.customer': 'Customer',
    'orders.vendor': 'Vendor',
    'orders.total': 'Total',
    'orders.status': 'Status',
    'orders.payment': 'Payment',
    'orders.shipping': 'Shipping',
    'orders.actions': 'Actions',
    'orders.updateStatus': 'Update Status',
    'orders.print': 'Print',
    'orders.clearAll': 'Clear All',
    'orders.clearFilters': 'Clear Filters',
    'orders.sortBy': 'Sort by',
    'orders.cancelled': 'Cancelled',
    'orders.readyToShip': 'Ready to Ship',
    'orders.paid': 'Paid',
    'orders.unpaid': 'Unpaid',
    'orders.refunded': 'Refunded',
    
    // Finances
    'finances.title': 'Financial Analytics',
    'finances.subtitle': 'Track revenue, commissions, and vendor payouts',
    'finances.totalRevenue': 'Total Revenue',
    'finances.platformCommission': 'Platform Commission',
    'finances.vendorPayout': 'Vendor Payout',
    /** Top stat card: sum of vendor-side earnings (order total − platform commission). */
    'finances.commissionPayout': 'Vendor commission earned',
    'finances.commissionPayoutHint': 'Total vendor share after platform commission',
    'finances.pendingPayouts': 'Pending Payouts',
    'finances.overview': 'Overview',
    'finances.transactions': 'Transactions',
    'finances.vendorPayouts': 'Vendor Payouts',
    'finances.collaboratorPayouts': 'Collaborator Payouts',
    'finances.paymentMethods': 'Payment Methods',
    'finances.revenueAnalytics': 'Revenue Analytics',
    'finances.commissionBreakdown': 'Commission Breakdown',
    'finances.paymentMethodsDistribution': 'Payment Methods Distribution',
    'finances.searchPlaceholder': 'Search by ID, customer, or vendor...',
    'finances.allStatus': 'All Status',
    'finances.allMethods': 'All Methods',
    'finances.dateRange': 'Date Range',
    'finances.filterByDate': 'Filter by date',
    'finances.filterByDateHint': 'Stats, charts, and tables use orders in this range. Leave unset for all time.',
    'finances.statCardDateHint': 'Choose start and end date. Applies to this card only.',
    'finances.allTime': 'All time',
    'finances.selectEndDate': 'Select end date',
    'finances.clearDateFilter': 'Clear dates',
    'admin.dateFilter.hintOrders': 'Filters the order list by order date.',
    'admin.dateFilter.hintTransactions': 'Filters the transaction table by transaction date.',
    'admin.dateFilter.hintMarketing': 'Filters campaigns by created date.',
    'finances.clearFilters': 'Clear',
    'finances.export': 'Export',
    'finances.transactionId': 'Transaction ID',
    'finances.date': 'Date',
    'finances.customer': 'Customer',
    'finances.vendor': 'Vendor',
    'finances.method': 'Method',
    'finances.amount': 'Amount',
    'finances.commission': 'Commission',
    'finances.status': 'Status',
    'finances.actions': 'Actions',
    'finances.noTransactions': 'No transactions found',
    'finances.transactionDetails': 'Transaction Details',
    'finances.products': 'Products',
    'finances.subtotal': 'Subtotal',
    'finances.gatewayFee': 'Gateway Fee',
    'finances.shippingAddress': 'Shipping Address',
    'finances.trackingNumber': 'Tracking Number',
    'finances.completed': 'Completed',
    'finances.pending': 'Pending',
    'finances.failed': 'Failed',
    'finances.showing': 'Showing',
    'finances.of': 'of',
    'finances.revenue': 'Revenue',
    'finances.email': 'Email',
    'finances.orders': 'Orders',
    'finances.payout': 'Payout',
    'finances.noVendorPayouts': 'No vendor payouts found',
    'finances.collaboratorPayoutsComingSoon': 'Collaborator payouts coming soon',
    'finances.collaboratorPayoutsDesc': 'This feature will be available in the next update',
    'finances.transactions_count': 'transactions',
    'finances.ofTotal': 'of total',
    'finances.vsLastMonth': 'vs last month',
    'finances.outgoing': 'Outgoing',
    'finances.dueDate': 'Due Feb 15',
    'finances.7days': '7 Days',
    'finances.30days': '30 Days',
    'finances.90days': '90 Days',
    
    // Vendors
    'vendors.title': 'Vendors',
    'vendors.subtitle': 'Manage your vendor partners and their products',
    'vendors.reviewApplications': 'Review Applications',
    'vendors.addVendor': 'Add Vendor',
    'vendors.filterByVendor': 'Filter by vendor',
    'vendors.allVendors': 'All Vendors',
    'vendors.newStorefronts': 'New: Independent Vendor Storefronts',
    'vendors.storefrontsDesc': 'Each vendor now has their own separate, fully-branded storefront! Click on any vendor and select "Manage Storefront" to configure their unique online store. Migoo handles all ERP operations while vendors maintain their brand identity.',
    'vendors.totalVendors': 'Total Vendors',
    'vendors.active': 'Active',
    'vendors.inactive': 'Inactive',
    'vendors.pending': 'Pending',
    'vendors.totalRevenue': 'Total Revenue',
    'vendors.commissionEarned': 'Commission Earned',
    'vendors.searchPlaceholder': 'Search vendors by name, email, or location...',
    'vendors.allStatus': 'All Status',
    'vendors.export': 'Export',
    'vendors.vendor': 'VENDOR',
    'vendors.contact': 'CONTACT',
    'vendors.location': 'LOCATION',
    'vendors.products': 'PRODUCTS',
    'vendors.revenue': 'REVENUE',
    'vendors.commission': 'COMMISSION',
    'vendors.status': 'STATUS',
    'vendors.joined': 'JOINED',
    'vendors.actions': 'ACTIONS',
    
    // Collaborators
    'collaborators.title': 'Collaborators',
    'collaborators.subtitle': 'Manage collaborators and their permissions',
    'collaborators.addCollaborator': 'Add Collaborator',
    'collaborators.reviewApplications': 'Review Applications',
    'collaborators.totalCollaborators': 'Total Collaborators',
    'collaborators.active': 'Active',
    'collaborators.inactive': 'Inactive',
    'collaborators.pending': 'Pending',
    'collaborators.liveNow': 'Live Now',
    'collaborators.scheduled': 'Scheduled',
    'collaborators.offline': 'Offline',
    'collaborators.filterByCollaborator': 'Filter by collaborator',
    'collaborators.allCollaborators': 'All Collaborators',
    'collaborators.searchPlaceholder': 'Search collaborators...',
    'collaborators.allStatus': 'All Status',
    'collaborators.export': 'Export',
    'collaborators.name': 'NAME',
    'collaborators.email': 'EMAIL',
    'collaborators.role': 'ROLE',
    'collaborators.products': 'PRODUCTS',
    'collaborators.status': 'STATUS',
    'collaborators.joined': 'JOINED',
    'collaborators.actions': 'ACTIONS',
    'collaborators.viewProfile': 'View Profile',
    'collaborators.edit': 'Edit',
    'collaborators.sendEmail': 'Send Email',
    'collaborators.remove': 'Remove',
    'collaborators.followers': 'Followers',
    'collaborators.avgViewers': 'Avg Viewers',
    'collaborators.totalStreams': 'Total Streams',
    'collaborators.revenueGenerated': 'Revenue Generated',
    'collaborators.commission': 'Commission',
    'collaborators.noResults': 'No collaborators found',
    'collaborators.noResultsDesc': 'Try adjusting your search or filters',
    
    // Marketing
    'marketing.title': 'Promo Setting',
    'marketing.subtitle': 'Manage campaigns, discounts, and push notifications',
    'marketing.createCampaign': 'Create Campaign',
    'marketing.totalRevenue': 'Total Revenue',
    'marketing.activeCampaigns': 'Active Campaigns',
    'marketing.totalClicks': 'Total Clicks',
    'marketing.conversionRate': 'Conversion Rate',
    'marketing.searchPlaceholder': 'Search campaigns...',
    'marketing.allTypes': 'All Types',
    'marketing.allStatus': 'All Status',
    'marketing.allCreators': 'All Creators',
    'marketing.export': 'Export',
    'marketing.performance': 'Performance',
    'marketing.campaignsByCreator': 'Campaigns by Creator',
    'marketing.admin': 'Admin',
    'marketing.vendors': 'Vendors',
    'marketing.collaborators': 'Collaborators',
    'marketing.vendor': 'Vendor',
    'marketing.collaborator': 'Collaborator',
    'marketing.creator': 'Creator',
    'marketing.edit': 'Edit',
    'marketing.delete': 'Delete',
    'marketing.duplicate': 'Duplicate',
    'marketing.view': 'View Details',
    'marketing.announcementBar': 'Announcement Bar',
    'marketing.announcementBarDesc': 'Display important messages at the top of your store',
    'marketing.enableAnnouncement': 'Enable Announcement Bar',
    'marketing.announcementText': 'Announcement Text',
    'marketing.announcementTextPlaceholder': 'e.g., Free shipping on orders over $50! 🚚',
    'marketing.backgroundColor': 'Background Color',
    'marketing.textColor': 'Text Color',
    'marketing.saveChanges': 'Save Changes',
    'marketing.campaignName': 'Campaign Name',
    'marketing.campaignCode': 'Code',
    'marketing.discount': 'Discount',
    'marketing.used': 'Used',
    'marketing.conversions': 'Conversions',
    'marketing.revenue': 'Revenue',
    'marketing.clicks': 'Clicks',
    'marketing.targetAudience': 'Target Audience',
    'marketing.allCustomers': 'All Customers',
    'marketing.newCustomers': 'New Customers',
    'marketing.vipCustomers': 'VIP Customers',
    'marketing.cartAbandoners': 'Cart Abandoners',
    'marketing.usage': 'Usage',
    'marketing.limit': 'Limit',
    'marketing.coupon': 'Coupon',
    'marketing.seasonal': 'Seasonal',
    'marketing.discountCode': 'Discount Code',
    'marketing.pushNotification': 'Push Notification',
    
    // Customers
    'customers.title': 'Customers',
    'customers.subtitle': 'Manage your customer relationships',
    'customers.addCustomer': 'Add Customer',
    'customers.totalCustomers': 'Total Customers',
    'customers.newThisMonth': 'New This Month',
    'customers.activeCustomers': 'Active',
    'customers.totalFollowers': 'Total Followers',
    'customers.totalSpent': 'Total Spent',
    'customers.searchPlaceholder': 'Search customers...',
    'customers.allStatus': 'All Status',
    'customers.export': 'Export',
    'customers.customer': 'CUSTOMER',
    'customers.email': 'EMAIL',
    'customers.orders': 'ORDERS',
    'customers.lastOrder': 'LAST ORDER',
    'customers.status': 'STATUS',
    'customers.actions': 'ACTIONS',
    'customers.vip': 'VIP',
    'customers.regular': 'Regular',
    'customers.new': 'New',
    'customers.active': 'Active',
    'customers.inactive': 'Inactive',
    'customers.blocked': 'Blocked',
    'customers.viewProfile': 'View Profile',
    'customers.sendEmail': 'Send Email',
    'customers.blockCustomer': 'Block Customer',
    'customers.deleteCustomer': 'Delete Customer',
    'customers.tier': 'Tier',
    'customers.location': 'Location',
    'customers.joinDate': 'Join Date',
    'customers.lastVisit': 'Last Visit',
    'customers.phone': 'Phone',
    'customers.filterStatus': 'Filter by status',
    'customers.filterTier': 'Filter by tier',
    'customers.allTiers': 'All Tiers',
    'customers.selected': 'selected',
    'customers.bulkActions': 'Bulk Actions',
    
    // Vendor
    'vendor.title': 'Vendors',
    'vendor.subtitle': 'Manage your vendor relationships',
    'vendor.addVendor': 'Add Vendor',
    'vendor.reviewApplications': 'Review Applications',
    'vendor.review': 'Review',
    'vendor.totalVendors': 'Total Vendors',
    'vendor.active': 'Active',
    'vendor.pending': 'Pending review',
    'vendor.pendingSubVendorsOnly': '{count} vendor account(s) with pending status',
    'vendor.pendingSubAppsOnly': '{count} application(s) awaiting review',
    'vendor.pendingSubBoth': '{vendorCount} vendor account(s) · {appCount} application(s)',
    'vendor.inactive': 'Inactive',
    'vendor.restrictedVendorStat': 'Suspended · banned',
    'vendor.totalRevenue': 'Total Revenue',
    'vendor.totalProducts': 'Total Products',
    'vendor.searchPlaceholder': 'Search vendors...',
    'vendor.name': 'NAME',
    'vendor.email': 'EMAIL',
    'vendor.products': 'PRODUCTS',
    'vendor.revenue': 'REVENUE',
    'vendor.commission': 'COMMISSION',
    'vendor.status': 'STATUS',
    'vendor.joined': 'JOINED',
    'vendor.actions': 'ACTIONS',
    'vendor.viewProfile': 'View Profile',
    'vendor.edit': 'Edit',
    'vendor.sendEmail': 'Send Email',
    'vendor.suspend': 'Suspend',
    'vendor.delete': 'Delete',
    'vendor.deleteConfirm': 'Are you sure you want to delete this vendor?',
    'vendor.deleteSuccess': '✅ Vendor deleted successfully!',
    'vendor.deleteError': 'Failed to delete vendor',
    'vendor.bulkDeleteConfirm': 'Are you sure you want to delete {count} vendor(s)?',
    'vendor.bulkDeleteSuccess': '✅ {count} vendor(s) deleted successfully!',
    'vendor.bulkDeleteError': 'Failed to delete vendors',
    'vendor.noResults': 'No vendors found',
    'vendor.filterStatus': 'Filter by status',
    'vendor.allStatus': 'All statuses',
    'vendor.export': 'Export',
    'vendor.suspended': 'Suspended',
    'vendor.banned': 'Banned',
    
    // Blog Category
    'blogCategory.title': 'Blog Categories',
    'blogCategory.subtitle': 'Organize your blog content',
    'blogCategory.addCategory': 'Add Category',
    'blogCategory.totalCategories': 'Total Categories',
    'blogCategory.totalPosts': 'Total Posts',
    'blogCategory.searchPlaceholder': 'Search categories...',
    'blogCategory.category': 'CATEGORY',
    'blogCategory.slug': 'SLUG',
    'blogCategory.posts': 'POSTS',
    'blogCategory.status': 'STATUS',
    'blogCategory.created': 'CREATED',
    'blogCategory.actions': 'ACTIONS',
    'blogCategory.edit': 'Edit',
    'blogCategory.delete': 'Delete',
    'blogCategory.addNewCategory': 'Add New Category',
    'blogCategory.categoryName': 'Category Name',
    'blogCategory.categoryNamePlaceholder': 'e.g., Business Tips',
    'blogCategory.categorySlug': 'Slug',
    'blogCategory.categorySlugPlaceholder': 'e.g., business-tips',
    'blogCategory.categoryDescription': 'Description',
    'blogCategory.categoryDescriptionPlaceholder': 'Brief description of this category...',
    'blogCategory.parentCategory': 'Parent Category',
    'blogCategory.none': 'None',
    'blogCategory.cancel': 'Cancel',
    'blogCategory.createCategory': 'Create Category',
    'blogCategory.saveChanges': 'Save Changes',
    
    // Add Blog Post
    'addBlogPost.title': 'Create New Blog Post',
    'addBlogPost.editTitle': 'Edit Blog Post',
    'addBlogPost.back': 'Back to Posts',
    'addBlogPost.saveDraft': 'Save as Draft',
    'addBlogPost.publish': 'Publish',
    'addBlogPost.update': 'Update Post',
    'addBlogPost.basicInfo': 'Basic Information',
    'addBlogPost.postTitle': 'Post Title',
    'addBlogPost.postTitlePlaceholder': 'Enter an engaging title...',
    'addBlogPost.excerpt': 'Excerpt',
    'addBlogPost.excerptPlaceholder': 'Write a brief summary (shown in preview cards)...',
    'addBlogPost.content': 'Content',
    'addBlogPost.contentPlaceholder': 'Write your blog post content here...',
    'addBlogPost.formatting': 'Formatting',
    'addBlogPost.bold': 'Bold',
    'addBlogPost.italic': 'Italic',
    'addBlogPost.heading': 'Heading',
    'addBlogPost.bulletList': 'Bullet List',
    'addBlogPost.numberedList': 'Numbered List',
    'addBlogPost.quote': 'Quote',
    'addBlogPost.code': 'Code',
    'addBlogPost.link': 'Link',
    'addBlogPost.media': 'Media',
    'addBlogPost.coverImage': 'Cover Image',
    'addBlogPost.coverImageDesc': 'This image will be displayed as the post thumbnail',
    'addBlogPost.uploadImage': 'Upload Image',
    'addBlogPost.pasteUrl': 'Paste URL',
    'addBlogPost.imageUrlPlaceholder': 'Paste image URL...',
    'addBlogPost.addImage': 'Add Image',
    'addBlogPost.addToContent': 'Add to Content',
    'addBlogPost.insertImage': 'Insert Image',
    'addBlogPost.addVideo': 'Add Video',
    'addBlogPost.videoUrlPlaceholder': 'Paste video URL (YouTube, Vimeo, etc.)...',
    'addBlogPost.insertVideo': 'Insert Video',
    'addBlogPost.seoSettings': 'SEO Settings',
    'addBlogPost.metaDescription': 'Meta Description',
    'addBlogPost.metaDescriptionPlaceholder': 'Brief description for search engines (150-160 characters)...',
    'addBlogPost.tags': 'Tags',
    'addBlogPost.tagsDesc': 'Add tags to help readers find your content',
    'addBlogPost.addTagPlaceholder': 'Add a tag...',
    'addBlogPost.addTag': 'Add',
    'addBlogPost.publishSettings': 'Publishing Settings',
    'addBlogPost.status': 'Status',
    'addBlogPost.draft': 'Draft',
    'addBlogPost.published': 'Published',
    'addBlogPost.scheduled': 'Scheduled',
    'addBlogPost.category': 'Category',
    'addBlogPost.selectCategory': 'Select category',
    'addBlogPost.uncategorized': 'Uncategorized',
    'addBlogPost.author': 'Author',
    'addBlogPost.authorPlaceholder': 'Author name',
    'addBlogPost.publishDate': 'Publish Date',
    'addBlogPost.featured': 'Featured Post',
    'addBlogPost.featuredDesc': 'Show this post prominently on your blog',
    'addBlogPost.comments': 'Allow Comments',
    
    // Campaign Form
    'campaignForm.createTitle': 'Create Campaign',
    'campaignForm.editTitle': 'Edit Campaign',
    'campaignForm.back': 'Back',
    'campaignForm.saveDraft': 'Save Draft',
    'campaignForm.create': 'Create Campaign',
    'campaignForm.save': 'Save Changes',
    'campaignForm.basicInfo': 'Basic Information',
    'campaignForm.campaignName': 'Campaign Name',
    'campaignForm.campaignNamePlaceholder': 'e.g., Summer Sale 2026',
    'campaignForm.campaignType': 'Campaign Type',
    'campaignForm.discount': 'Discount/Coupon',
    'campaignForm.pushNotification': 'Push Notification',
    'campaignForm.seasonal': 'Seasonal Campaign',
    'campaignForm.discountSettings': 'Discount Settings',
    'campaignForm.discountCode': 'Discount Code',
    'campaignForm.discountCodePlaceholder': 'e.g., SUMMER2026',
    'campaignForm.discountType': 'Discount Type',
    'campaignForm.percentage': 'Percentage',
    'campaignForm.fixedAmount': 'Fixed Amount',
    'campaignForm.discountValue': 'Discount Value',
    'campaignForm.targetAudience': 'Target Audience',
    'campaignForm.allCustomers': 'All Customers',
    'campaignForm.newCustomers': 'New Customers',
    'campaignForm.vipCustomers': 'VIP Customers',
    'campaignForm.notificationSettings': 'Notification Settings',
    'campaignForm.notificationTitle': 'Notification Title',
    'campaignForm.notificationTitlePlaceholder': 'e.g., Flash Sale Alert! 🔥',
    'campaignForm.notificationMessage': 'Message',
    'campaignForm.notificationMessagePlaceholder': 'Write your notification message...',
    'campaignForm.sendImmediately': 'Send Immediately',
    'campaignForm.schedule': 'Schedule for Later',
    'campaignForm.scheduledDate': 'Scheduled Date & Time',
    
    // Auth Modal
    'auth.welcomeBack': 'Welcome back',
    'auth.signInContinue': 'Sign in to continue',
    'auth.createAccount': 'Create your account',
    'auth.getStarted': 'Get started with Migoo',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Enter your full name',
    'auth.phoneNumber': 'Phone Number',
    'auth.phoneNumberPlaceholder': '+95 9 XXX XXX XXX',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.orContinueWith': 'Or continue with',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.agreeToTerms': 'By signing up, you agree to our Terms of Service and Privacy Policy',
    
    // Auth - Login
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to manage your Migoo platform',
    'auth.login.email': 'Email Address',
    'auth.login.emailPlaceholder': 'owner@migoo.com',
    'auth.login.password': 'Password',
    'auth.login.passwordPlaceholder': 'Enter your password',
    'auth.login.forgotPassword': 'Forgot Password?',
    'auth.login.signIn': 'Sign In',
    'auth.login.signingIn': 'Signing in...',
    'auth.login.error': 'Login failed. Please check your credentials.',
    'auth.login.agree': 'I agree to the Terms and Conditions',
    'auth.login.agreeError': 'You must agree to the Terms and Conditions to continue.',
    'auth.login.rememberMe': 'Keep me signed in',
    'auth.login.rememberMeHint': 'Stay logged in on this device',
    
    // Auth - Forgot Password
    'auth.forgotPassword.title': 'Reset Password',
    'auth.forgotPassword.subtitle': 'Choose how you want to reset your password',
    'auth.forgotPassword.back': 'Back to Login',
    'auth.forgotPassword.viaEmail': 'Via Email',
    'auth.forgotPassword.viaSms': 'Via SMS',
    'auth.forgotPassword.emailLabel': 'Email Address',
    'auth.forgotPassword.emailPlaceholder': 'owner@migoo.com',
    'auth.forgotPassword.emailHint': 'We\'ll send a password reset link to this email',
    'auth.forgotPassword.emailOtpHint': 'We\'ll send a 6-digit OTP code to this email',
    'auth.forgotPassword.phoneLabel': 'Phone Number',
    'auth.forgotPassword.smsHint': 'We\'ll send an OTP code to this number',
    'auth.forgotPassword.sendResetLink': 'Send Reset Link',
    'auth.forgotPassword.sendOtp': 'Send OTP Code',
    'auth.forgotPassword.sending': 'Sending...',
    'auth.forgotPassword.error': 'Failed to send reset instructions',
    'auth.forgotPassword.otpError': 'Invalid or expired OTP code',
    'auth.forgotPassword.enterOtp': 'Enter Verification Code',
    'auth.forgotPassword.otpSentEmail': 'We\'ve sent a 6-digit code to your email',
    'auth.forgotPassword.otpSentPhone': 'We\'ve sent a 6-digit code to your phone',
    'auth.forgotPassword.otpCode': 'Verification Code',
    'auth.forgotPassword.otpHint': 'Enter the 6-digit code you received',
    'auth.forgotPassword.verifyOtp': 'Verify Code',
    'auth.forgotPassword.verifying': 'Verifying...',
    'auth.forgotPassword.resendOtp': 'Resend Code',
    'auth.forgotPassword.successTitle': 'Check Your Inbox!',
    'auth.forgotPassword.emailSent': 'Password reset link sent! Check your email.',
    'auth.forgotPassword.checkEmail': 'We\'ve sent a password reset link to your email. Click the link to reset your password.',
    'auth.forgotPassword.smsSent': 'We\'ve sent an OTP code to your phone. Enter the code to reset your password.',
    'auth.forgotPassword.backToLogin': 'Back to Login',
    'auth.forgotPassword.sendReset': 'Send Reset Link',
    'auth.forgotPassword.setupWarning': 'SMS requires Twilio setup in Supabase. Use Email instead for instant delivery.',
    'auth.forgotPassword.emailRecommended': 'Email OTP is ready to use! Check your inbox for the 6-digit code (may take 1-2 minutes).',
    
    // Auth - Reset Password
    'auth.resetPassword.title': 'Create New Password',
    'auth.resetPassword.subtitle': 'Enter your new password below',
    'auth.resetPassword.newPassword': 'New Password',
    'auth.resetPassword.passwordPlaceholder': 'Enter new password',
    'auth.resetPassword.confirmPassword': 'Confirm New Password',
    'auth.resetPassword.confirmPasswordPlaceholder': 'Re-enter new password',
    'auth.resetPassword.passwordHint': 'Must be at least 8 characters',
    'auth.resetPassword.update': 'Update Password',
    'auth.resetPassword.updating': 'Updating...',
    'auth.resetPassword.error': 'Failed to reset password',
    'auth.resetPassword.passwordMismatch': 'Passwords do not match',
    'auth.resetPassword.passwordTooShort': 'Password must be at least 8 characters',
    'auth.resetPassword.successTitle': 'Password Updated!',
    'auth.resetPassword.successMessage': 'Your password has been successfully reset.',
    'auth.resetPassword.redirecting': 'Redirecting to login...',
    
    // Auth - Setup
    'auth.setup.title': 'Setup Super Admin',
    'auth.setup.subtitle': 'Create your owner account (one-time only)',
    'auth.setup.name': 'Full Name',
    'auth.setup.namePlaceholder': 'Your Name',
    'auth.setup.email': 'Email Address',
    'auth.setup.emailPlaceholder': 'owner@migoo.com',
    'auth.setup.phone': 'Phone Number (Optional)',
    'auth.setup.password': 'Password',
    'auth.setup.passwordPlaceholder': 'Create a strong password',
    'auth.setup.confirmPassword': 'Confirm Password',
    'auth.setup.confirmPasswordPlaceholder': 'Re-enter your password',
    'auth.setup.create': 'Create Super Admin Account',
    'auth.setup.creating': 'Creating account...',
    'auth.setup.error': 'Failed to create account. Please try again.',
    'auth.setup.passwordMismatch': 'Passwords do not match',
    'auth.setup.passwordTooShort': 'Password must be at least 8 characters',
    'auth.setup.info': 'This page will self-destruct after first use',
    'auth.setup.successTitle': 'Account Created Successfully!',
    'auth.setup.successMessage': 'Your super admin account has been created. You can now login.',
    'auth.setup.goToLogin': 'Go to Login',
    'auth.setup.footerPrompt': 'Already have an account?',
    'auth.setup.footerSignIn': 'Sign in',
    
    // Auth - Change Password
    'auth.changePassword.title': 'Change Password',
    'auth.changePassword.subtitle': 'You must change your temporary password',
    'auth.changePassword.newPassword': 'New Password',
    'auth.changePassword.passwordPlaceholder': 'Enter new password',
    'auth.changePassword.confirmPassword': 'Confirm New Password',
    'auth.changePassword.confirmPasswordPlaceholder': 'Re-enter new password',
    'auth.changePassword.passwordHint': 'Must be at least 8 characters',
    'auth.changePassword.update': 'Update Password',
    'auth.changePassword.updating': 'Updating...',
    'auth.changePassword.error': 'Failed to update password',
    'auth.changePassword.passwordMismatch': 'Passwords do not match',
    'auth.changePassword.passwordTooShort': 'Password must be at least 8 characters',
    
    // User Management
    'userManagement.title': 'User Management',
    'userManagement.subtitle': 'Create and manage user accounts',
    'userManagement.addUser': 'Add User',
    'userManagement.totalUsers': 'Total Users',
    'userManagement.name': 'Name',
    'userManagement.email': 'Email',
    'userManagement.phone': 'Phone',
    'userManagement.role': 'Role',
    'userManagement.actions': 'Actions',
    'userManagement.edit': 'Edit',
    'userManagement.delete': 'Delete',
    'userManagement.resetPassword': 'Reset Password',
    'userManagement.confirmDelete': 'Are you sure you want to delete this user?',
    
    // User Form
    'userForm.addTitle': 'Add New User',
    'userForm.editTitle': 'Edit User',
    'userForm.name': 'Full Name',
    'userForm.namePlaceholder': 'John Doe',
    'userForm.email': 'Email Address',
    'userForm.emailPlaceholder': 'john@example.com',
    'userForm.phone': 'Phone Number',
    'userForm.phonePlaceholder': '+95 9 XXX XXX XXX',
    'userForm.password': 'Temporary Password',
    'userForm.passwordPlaceholder': 'Will be generated automatically',
    'userForm.role': 'User Role',
    'userForm.selectRole': 'Select a role',
    'userForm.store': 'Assign Store (for Vendor Admin/Collaborator)',
    'userForm.selectStore': 'Select a store',
    'userForm.cancel': 'Cancel',
    'userForm.save': 'Save User',
    'userForm.create': 'Create User',
    'userForm.creating': 'Creating...',
    'userForm.saving': 'Saving...',
    
    // Roles
    'role.superAdmin': 'Super Admin',
    'role.superAdmin.desc': 'Full access to all vendors and platform settings',
    'role.vendorAdmin': 'Vendor Admin',
    'role.vendorAdmin.desc': 'Manage their own store, products, and orders',
    'role.collaborator': 'Collaborator',
    'role.collaborator.desc': 'Limited access to help manage a vendor store',
    
    // Inventory Adjust Dialog
    'inventory.dialog.adjust.title': 'Adjust Inventory',
    'inventory.dialog.adjust.description': 'Update stock quantity and SKU for',
    'inventory.dialog.currentStock': 'Current Stock',
    'inventory.dialog.available': 'Available',
    'inventory.dialog.adjustment': 'Adjustment Quantity',
    'inventory.dialog.adjustmentPlaceholder': 'Enter quantity (use - for decrease)',
    'inventory.dialog.adjustmentHint': 'Use positive numbers to add stock, negative to remove',
    'inventory.dialog.preview': 'Preview:',
    'inventory.dialog.newStock': 'New stock:',
    'inventory.dialog.sku': 'SKU',
    'inventory.dialog.skuPlaceholder': 'Enter SKU',
    'inventory.dialog.skuHint': 'Update the SKU number if needed',
    'inventory.dialog.cancel': 'Cancel',
    'inventory.dialog.save': 'Save Changes',
    'inventory.dialog.saving': 'Saving...',
    
    // Inventory Bulk Adjust Dialog
    'inventory.dialog.bulk.title': 'Bulk Adjust Inventory',
    'inventory.dialog.bulk.description': 'Adjust stock levels for',
    'inventory.dialog.bulk.selectedItems': 'Selected Items:',
    'inventory.dialog.bulk.current': 'Current:',
    'inventory.dialog.bulk.adjustmentHint': 'This adjustment will be applied to all',
    'inventory.dialog.bulk.selectedItemsHint': 'selected items',
    'inventory.dialog.bulk.previewChanges': 'Preview Changes:',
    'inventory.dialog.bulk.andMore': '...and',
    'inventory.dialog.bulk.moreItems': 'more items',
    'inventory.dialog.bulk.applyToAll': 'Apply to All Selected',
    
    // Inventory Success/Error Messages
    'inventory.success.adjusted': 'Inventory adjusted successfully',
    'inventory.success.bulkAdjusted': 'Bulk inventory adjustment completed',
    'inventory.error.adjust': 'Failed to adjust inventory',
    'inventory.error.load': 'Failed to load inventory data',
    'inventory.error.invalidQty': 'Please enter a valid quantity',
  },
  zh: {
    // Settings Page
    'settings.title': '设置',
    'settings.subtitle': '管理您的商店偏好和配置',
    'settings.general': '常规',
    'settings.users': '用户',
    'settings.appearance': '外观',
    
    // General Tab
    'settings.general.storeInfo': '商店信息',
    'settings.general.storeName': '商店名称',
    'settings.general.contactEmail': '联系邮箱',
    'settings.general.contactEmailHint': '客户将使用此邮箱与您联系',
    'settings.general.phoneNumber': '电话号码',
    'settings.general.storeAddress': '商店地址',
    'settings.general.regionalSettings': '区域设置',
    'settings.general.currency': '货币',
    'settings.general.timezone': '时区',
    'settings.general.language': '语言',
    'settings.general.languageHint': '选择您的界面首选语言',
    'settings.general.saveChanges': '保存更改',

    // Currency & timezone (Settings selects)
    'currency.MMK': '缅甸元 (MMK)',
    'currency.CNY': '人民币 (CNY)',
    'currency.USD': '美元 (USD)',
    'timezone.America/New_York': '美国东部（纽约）',
    'timezone.America/Chicago': '美国中部（芝加哥）',
    'timezone.America/Denver': '美国山地（丹佛）',
    'timezone.America/Los_Angeles': '美国太平洋（洛杉矶）',
    'timezone.Europe/London': '伦敦',
    'timezone.Asia/Tokyo': '东京',
    'timezone.Asia/Yangon': '仰光',
    
    // Language Options
    'language.english': 'English (英语)',
    'language.chinese': '简体中文',
    
    // Users Tab
    'settings.users.totalUsers': '总用户数',
    'settings.users.active': '活跃',
    'settings.users.addUser': '添加用户',
    'settings.users.user': '用户',
    'settings.users.role': '角色',
    'settings.users.status': '状态',
    'settings.users.lastActive': '最后活跃',
    'settings.users.active.status': '活跃',
    'settings.users.inactive.status': '未活跃',
    'settings.users.viewProfile': '查看资料',
    'settings.users.editUser': '编辑用户',
    'settings.users.deleteUser': '删除用户',
    'settings.users.deleteConfirm': '您确定要删除此用户吗？',
    
    // User Dialog
    'settings.users.dialog.add.title': '添加新用户',
    'settings.users.dialog.add.description': '创建具有角色和权限的新用户帐户。',
    'settings.users.dialog.edit.title': '编辑用户',
    'settings.users.dialog.edit.description': '更新用户信息和角色。',
    'settings.users.dialog.fullName': '全名',
    'settings.users.dialog.fullNamePlaceholder': '例如：张三',
    'settings.users.dialog.email': '电子邮箱',
    'settings.users.dialog.emailPlaceholder': 'zhangsan@example.com',
    'settings.users.dialog.emailHint': '用户将在此邮箱收到登录凭据',
    'settings.users.dialog.role': '角色',
    'settings.users.dialog.avatar': '头像',
    'settings.users.dialog.cancel': '取消',
    'settings.users.dialog.save': '保存更改',
    'settings.users.dialog.add': '添加用户',
    
    // Roles
    'role.storeOwner': '店主',
    'role.storeOwner.desc': '拥有完全商店访问权限和控制权的企业主',
    'role.storeOwner.full': '店主 - 完全访问权限',
    'role.administrator': '管理员',
    'role.administrator.desc': '管理产品、订单和用户（店主设置除外）',
    'role.administrator.full': '管理员 - 管理运营',
    'role.dataEntry': '数据录入员',
    'role.dataEntry.desc': '仅添加和编辑产品、管理库存',
    'role.dataEntry.full': '数据录入员 - 有限访问权限',
    'role.developer': '开发人员',
    'role.developer.desc': '集成和自定义的技术访问权限',
    'role.developer.full': '开发人员 - 技术访问权限',
    'role.productManager': '产品经理',
    'role.productManager.desc': '定义和管理产品策略和路线图',
    'role.productManager.full': '产品经理 - 策略和路图',
    
    // Role Permissions
    'settings.users.rolePermissions': '角色权限',
    'role.storeOwner.permissions': '拥有完全商店访问权限和控制权的企业主，包括：',
    'role.storeOwner.perm1': '管理所有产品、订单和内容',
    'role.storeOwner.perm2': '访问所有财务数据和报告',
    'role.storeOwner.perm3': '添加、编辑和删除用户',
    'role.storeOwner.perm4': '修改商店设置和配置',
    'role.storeOwner.perm5': '无法被删除或停用',
    'role.administrator.permissions': '管理日常运营，包括：',
    'role.administrator.perm1': '管理产品、类别和库存',
    'role.administrator.perm2': '处理和管理订单',
    'role.administrator.perm3': '访问营销和博客功能',
    'role.administrator.perm4': '查看报告和分析',
    'role.administrator.perm5': '无法访问店主设置或财务数据',
    'role.dataEntry.permissions': '数据管理的有限访问权限：',
    'role.dataEntry.perm1': '添加和编辑产品',
    'role.dataEntry.perm2': '管理库存级别',
    'role.dataEntry.perm3': '更新产品信息',
    'role.dataEntry.perm4': '无法删除产品或访问订单',
    'role.dataEntry.perm5': '无法访问设置、用户或财务数据',
    'role.developer.permissions': '集成和自定义的技术访问权限：',
    'role.developer.perm1': '访问API文档和工具',
    'role.developer.perm2': '实现自定义功能和集成',
    'role.developer.perm3': '调试和排查技术问题',
    'role.developer.perm4': '无法访问用户数据或财务信息',
    'role.productManager.permissions': '定义和管理产品策略和路线图：',
    'role.productManager.perm1': '制定产品愿景和目标',
    'role.productManager.perm2': '规划和优先级排序产品功能',
    'role.productManager.perm3': '与开发和营销团队协作',
    'role.productManager.perm4': '监控产品性能和反馈',
    'role.productManager.perm5': '无法访问用户数据或财务信息',
    
    // Appearance Tab
    'settings.appearance.theme': '主题',
    'settings.appearance.theme.light': '浅色',
    'settings.appearance.theme.dark': '深色',
    'settings.appearance.theme.auto': '自动',
    'settings.appearance.accentColor': '强调色',
    'settings.appearance.save': '保存外观',
    
    // Common
    'common.save': '保存',
    'common.all': '全部',
    
    // Navigation
    'nav.home': '首页',
    'nav.search': '搜索',
    'nav.product': '产品',
    'nav.orders': '订单',
    'nav.vendor': '供应商',
    'nav.collaborator': '合作者',
    'nav.discount': '折扣',
    'nav.promoSetting': '促销设置',
    'nav.marketing': '营销',
    'nav.liveStream': '直播',
    'nav.chat': '聊天',
    'nav.customers': '客户',
    'nav.finances': '财务',
    'nav.logistics': '物流',
    'nav.blogPost': '博客文章',
    'nav.settings': '设置',
    'nav.categories': '类别',
    'nav.inventory': '库存',
    'nav.blogCategory': '博客类别',
    
    // Footer
    'footer.createdBy': '创建者',
    'footer.role': '软件架构师',
    
    // Dashboard
    'dashboard.title': '仪表盘',
    'dashboard.welcome': '欢迎回来，{name}！以下是今天的活动情况。',
    'dashboard.viewReports': '查看报告',
    'dashboard.totalRevenue': '总收入',
    'dashboard.orders': '订单',
    'dashboard.customers': '客户',
    'dashboard.products': '产品',
    'dashboard.fromLastMonth': '上个月',
    'dashboard.salesOverview': '销售概览',
    'dashboard.salesOverviewDesc': '月度销售和订单趋势',
    'dashboard.topProducts': '热门产品',
    'dashboard.topProductsDesc': '本月表现最好的产品',
    'dashboard.recentOrders': '最近订单',
    'dashboard.latestOrders': '最新客户订单',
    'dashboard.viewAll': '查看全部',
    'dashboard.sales': '销售额',
    'dashboard.ordersLower': '订单数',
    'dashboard.orderId': '订单ID',
    'dashboard.customer': '客户',
    'dashboard.product': '产品',
    'dashboard.amount': '金额',
    'dashboard.status': '状态',
    
    // Products
    'products.title': '产品',
    'products.subtitle': '管理您的产品库存和详细信息',
    'products.addProduct': '添加产品',
    'products.allProducts': '所有产品',
    'products.vendor': '供应商',
    'products.collaborator': '合作者',
    'products.salesVolume': '销售量',
    'products.searchPlaceholder': '按名称或SKU搜索产品...',
    'products.allStatus': '所有状态',
    'products.active': '活跃',
    'products.offShelf': '下架',
    'products.newestFirst': '最新优先',
    'products.oldestFirst': '最旧优先',
    'products.sortByDate': '按日期排序',
    'products.inventory': '库存',
    'products.category': '类别',
    'products.price': '价格',
    'products.actions': '操作',
    'products.status': '状态',
    
    // Add Product
    'addProduct.back': '返回',
    'addProduct.title': '添加产品',
    'addProduct.cancel': '取消',
    'addProduct.save': '保存',
    'addProduct.productTitle': '标题',
    'addProduct.description': '描述',
    'addProduct.descriptionPlaceholder': '详细描述您的产品...',
    'addProduct.productStatus': '产品状态',
    'addProduct.productOrganization': '产品组织',
    'addProduct.productType': '产品类型',
    'addProduct.productTypePlaceholder': '例如：衬衫',
    'addProduct.categoryLabel': '类别',
    'addProduct.categoryPlaceholder': '加载类别...',
    'addProduct.selectCategory': '选择类别',
    'addProduct.vendorLabel': '供应商',
    'addProduct.vendorPlaceholder': '选择供应商',
    'addProduct.collaboratorLabel': '合作者',
    'addProduct.collaboratorPlaceholder': '选择合作者',
    'addProduct.tags': '标签',
    'addProduct.tagsHint': '添加标签以帮助组织和查找产品',
    'addProduct.enterTag': '输入标签...',
    'addProduct.add': '添加',
    'addProduct.media': '媒体',
    'addProduct.uploadTip': '提示：粘贴、拖放或点击添加图片',
    'addProduct.detailsHint': '添加产品详细信息、护理说明和尺寸信息',
    
    // Inventory
    'inventory.title': '库存',
    'inventory.totalQuantity': '总数量',
    'inventory.committedQuantity': '已承诺数量',
    'inventory.availableQuantity': '可用数量',
    'inventory.searchPlaceholder': '搜索库存',
    'inventory.allStock': '所有库存',
    'inventory.export': '导出',
    'inventory.product': '产品',
    'inventory.sku': 'SKU',
    'inventory.available': '可用',
    'inventory.committed': '已承诺',
    'inventory.onHand': '在手',
    'inventory.location': '位置',
    'inventory.actions': '操作',
    
    // Categories
    'categories.title': '类别',
    'categories.searchPlaceholder': '搜索类别',
    'categories.deleteTestData': '删除测试数据',
    'categories.deleteAll': '删除所有',
    'categories.addCategory': '添加类别',
    'categories.category': '类别',
    'categories.description': '描述',
    'categories.products': '产品',
    'categories.status': '状态',
    'categories.actions': '操作',
    'categories.active': '活跃',
    'categories.hidden': '隐藏',
    'categories.backToCategories': '返回类别',
    'categories.createNew': '创建新类别',
    'categories.createSubtitle': '添加类别并分配产品以组织您的库存',
    'categories.basicInfo': '基本信息',
    'categories.categoryName': '类别名称',
    'categories.categoryNamePlaceholder': '例如：电子产品、服装、家居园艺',
    'categories.descriptionLabel': '描述',
    'categories.descriptionPlaceholder': '描述哪些产品属于此类别...',
    'categories.categorySettings': '类别设置',
    'categories.statusLabel': '状态',
    'categories.statusActive': '活跃 - 对客户可见',
    'categories.coverPhoto': '封面照片',
    'categories.uploadText': '点击上传或拖放',
    'categories.uploadHint': 'PNG、JPG、GIF，最大5MB',
    'categories.createButton': '创建类别',
    'categories.cancelButton': '取消',
    
    // Orders
    'orders.title': '订单',
    'orders.subtitle': '管理和跟踪所有订单',
    'orders.loading': '加载中...',
    'orders.totalRevenue': '总收入',
    'orders.pending': '待处理',
    'orders.needsAttention': '需要关注',
    'orders.processing': '处理中',
    'orders.inProgress': '进行中',
    'orders.fulfilled': '已完成',
    'orders.completed': '完成',
    'orders.ordersTab': '订单',
    'orders.analyticsTab': '分析',
    'orders.allOrders': '所有订单',
    'orders.export': '导出',
    'orders.searchPlaceholder': '搜索订单...',
    'orders.newestFirst': '最新优先',
    'orders.oldestFirst': '最旧优先',
    'orders.allStatus': '所有状态',
    'orders.allPayment': '所有支付',
    'orders.allVendors': '所有供应商',
    'orders.from': '从',
    'orders.to': '到',
    'orders.order': '订单',
    'orders.date': '日期',
    'orders.customer': '客户',
    'orders.vendor': '供应商',
    'orders.total': '总计',
    'orders.status': '状态',
    'orders.payment': '支付',
    'orders.shipping': '发货',
    'orders.actions': '操作',
    'orders.updateStatus': '更新状态',
    'orders.print': '打印',
    'orders.clearAll': '清除所有',
    'orders.clearFilters': '清除筛选条件',
    'orders.sortBy': '排序依据',
    'orders.cancelled': '已取消',
    'orders.readyToShip': '准备发货',
    'orders.paid': '已支付',
    'orders.unpaid': '未支付',
    'orders.refunded': '已退款',
    
    // Finances
    'finances.title': '财务分析',
    'finances.subtitle': '跟踪收入、佣金和供应商付款',
    'finances.totalRevenue': '总收入',
    'finances.platformCommission': '平台佣金',
    'finances.vendorPayout': '供应商付款',
    'finances.commissionPayout': '供应商佣金收入',
    'finances.commissionPayoutHint': '扣除平台佣金后供应商所得合计',
    'finances.pendingPayouts': '待处理付款',
    'finances.overview': '概览',
    'finances.transactions': '交易',
    'finances.vendorPayouts': '供应商付款',
    'finances.collaboratorPayouts': '合作者付款',
    'finances.paymentMethods': '支付方式',
    'finances.revenueAnalytics': '收入分析',
    'finances.commissionBreakdown': '佣金细分',
    'finances.paymentMethodsDistribution': '支付方式分布',
    'finances.searchPlaceholder': '按ID、客户或供应商搜索...',
    'finances.allStatus': '所有状态',
    'finances.allMethods': '所有方式',
    'finances.dateRange': '日期范围',
    'finances.filterByDate': '按日期筛选',
    'finances.filterByDateHint': '统计、图表和表格仅包含该范围内的订单。不选则为全部时间。',
    'finances.statCardDateHint': '请选择开始与结束日期，仅影响本卡片数字。',
    'finances.allTime': '全部时间',
    'finances.selectEndDate': '请选择结束日期',
    'finances.clearDateFilter': '清除日期',
    'admin.dateFilter.hintOrders': '按订单日期筛选订单列表。',
    'admin.dateFilter.hintTransactions': '按交易日期筛选交易表。',
    'admin.dateFilter.hintMarketing': '按创建日期筛选活动。',
    'finances.clearFilters': '清除',
    'finances.export': '导出',
    'finances.transactionId': '交易ID',
    'finances.date': '日期',
    'finances.customer': '客户',
    'finances.vendor': '供应商',
    'finances.method': '方式',
    'finances.amount': '金额',
    'finances.commission': '佣金',
    'finances.status': '状态',
    'finances.actions': '操作',
    'finances.noTransactions': '未找到交易',
    'finances.transactionDetails': '交易详情',
    'finances.products': '产品',
    'finances.subtotal': '小计',
    'finances.gatewayFee': '网关费用',
    'finances.shippingAddress': '发货地址',
    'finances.trackingNumber': '跟踪号',
    'finances.completed': '已完成',
    'finances.pending': '待处理',
    'finances.failed': '失败',
    'finances.showing': '显示',
    'finances.of': '共',
    'finances.revenue': '收入',
    'finances.email': '电子邮件',
    'finances.orders': '订单',
    'finances.payout': '付款',
    'finances.noVendorPayouts': '未找到供应商付款',
    'finances.collaboratorPayoutsComingSoon': '合作者付款即将推出',
    'finances.collaboratorPayoutsDesc': '此功能将在下次更新中可用',
    'finances.transactions_count': '交易',
    'finances.ofTotal': '总计',
    'finances.vsLastMonth': '与上月相比',
    'finances.outgoing': '支出',
    'finances.dueDate': '2月15日到期',
    'finances.7days': '7天',
    'finances.30days': '30天',
    'finances.90days': '90天',
    
    // Vendors
    'vendors.title': '供应商',
    'vendors.subtitle': '管理您的供应商合作伙伴及其产品',
    'vendors.reviewApplications': '审核申请',
    'vendors.addVendor': '添加供应商',
    'vendors.filterByVendor': '按供应商筛选',
    'vendors.allVendors': '所有供应商',
    'vendors.newStorefronts': '新：独立供应商店面',
    'vendors.storefrontsDesc': '每个供应商现在都有自己的独立���完全品牌化的店面！点击任���供应商并选择“管理店面”以配置其独特的在线商店。Migoo处理所有ERP操作，而供应商保持其品牌身份。',
    'vendors.totalVendors': '总供应商数',
    'vendors.active': '活跃',
    'vendors.inactive': '不活跃',
    'vendors.pending': '待处理',
    'vendors.totalRevenue': '总收入',
    'vendors.commissionEarned': '获得佣金',
    'vendors.searchPlaceholder': '按名称、电子邮件或位置搜索供应商...',
    'vendors.allStatus': '所有状态',
    'vendors.export': '导出',
    'vendors.vendor': '供应商',
    'vendors.contact': '联系',
    'vendors.location': '位置',
    'vendors.products': '产品',
    'vendors.revenue': '收入',
    'vendors.commission': '佣金',
    'vendors.status': '状态',
    'vendors.joined': '加入日期',
    'vendors.actions': '操作',
    
    // Collaborators
    'collaborators.title': '合作者',
    'collaborators.subtitle': '管理合作者及其权限',
    'collaborators.addCollaborator': '添加合作者',
    'collaborators.reviewApplications': '审核申请',
    'collaborators.totalCollaborators': '总合作者数',
    'collaborators.active': '活跃',
    'collaborators.inactive': '不活跃',
    'collaborators.pending': '待处理',
    'collaborators.liveNow': '正在直播',
    'collaborators.scheduled': '已计划',
    'collaborators.offline': '离线',
    'collaborators.filterByCollaborator': '按合作者筛选',
    'collaborators.allCollaborators': '所有合作者',
    'collaborators.searchPlaceholder': '搜索合作者...',
    'collaborators.allStatus': '所有状态',
    'collaborators.export': '导出',
    'collaborators.name': '姓名',
    'collaborators.email': '电子邮件',
    'collaborators.role': '角色',
    'collaborators.products': '产品',
    'collaborators.status': '状态',
    'collaborators.joined': '加入日期',
    'collaborators.actions': '操作',
    'collaborators.viewProfile': '查看资料',
    'collaborators.edit': '编辑',
    'collaborators.sendEmail': '发送邮件',
    'collaborators.remove': '移除',
    'collaborators.followers': '关注者',
    'collaborators.avgViewers': '平均观看人数',
    'collaborators.totalStreams': '总直播次数',
    'collaborators.revenueGenerated': '生成收入',
    'collaborators.commission': '佣金',
    'collaborators.noResults': '未找到合作者',
    'collaborators.noResultsDesc': '尝试调整搜索或筛选条件',
    
    // Marketing
    'marketing.title': '促销设置',
    'marketing.subtitle': '管理营销活动、折扣和推送通知',
    'marketing.createCampaign': '创建营销活动',
    'marketing.totalRevenue': '总收入',
    'marketing.activeCampaigns': '活跃营销活动',
    'marketing.totalClicks': '总点击量',
    'marketing.conversionRate': '转化率',
    'marketing.searchPlaceholder': '搜索营销活动...',
    'marketing.allTypes': '所有类型',
    'marketing.allStatus': '所有状态',
    'marketing.allCreators': '所有创建者',
    'marketing.export': '导出',
    'marketing.performance': '性能',
    'marketing.campaignsByCreator': '按创建者分类的营销活动',
    'marketing.admin': '管理员',
    'marketing.vendors': '供应商',
    'marketing.collaborators': '合作者',
    'marketing.vendor': '供应商',
    'marketing.collaborator': '合作者',
    'marketing.creator': '创建者',
    'marketing.edit': '编辑',
    'marketing.delete': '删除',
    'marketing.duplicate': '复制',
    'marketing.view': '查看详情',
    'marketing.announcementBar': '公告栏',
    'marketing.announcementBarDesc': '在商店顶部显示重要消息',
    'marketing.enableAnnouncement': '启用公告栏',
    'marketing.announcementText': '公告文本',
    'marketing.announcementTextPlaceholder': '例如：订单满$50免运费！🚚',
    'marketing.backgroundColor': '背景颜色',
    'marketing.textColor': '文本颜色',
    'marketing.saveChanges': '保存更改',
    'marketing.campaignName': '营销活动名称',
    'marketing.campaignCode': '代码',
    'marketing.discount': '折扣',
    'marketing.used': '已使用',
    'marketing.conversions': '转化次数',
    'marketing.revenue': '收入',
    'marketing.clicks': '点击量',
    'marketing.targetAudience': '目标受众',
    'marketing.allCustomers': '所有客户',
    'marketing.newCustomers': '新客户',
    'marketing.vipCustomers': 'VIP客户',
    'marketing.cartAbandoners': '购物车放弃者',
    'marketing.usage': '使用量',
    'marketing.limit': '限制',
    'marketing.coupon': '优惠券',
    'marketing.seasonal': '季节性',
    'marketing.discountCode': '折扣码',
    'marketing.pushNotification': '推送通知',
    
    // Customers
    'customers.title': '客户',
    'customers.subtitle': '管理您的客户关系',
    'customers.addCustomer': '添加客户',
    'customers.totalCustomers': '总客户数',
    'customers.newThisMonth': '本月新增',
    'customers.activeCustomers': '活跃',
    'customers.totalFollowers': '总关注者',
    'customers.totalSpent': '总支出',
    'customers.searchPlaceholder': '搜索客户...',
    'customers.allStatus': '所有状态',
    'customers.export': '导出',
    'customers.customer': '客户',
    'customers.email': '电子邮件',
    'customers.orders': '订单',
    'customers.lastOrder': '最近订单',
    'customers.status': '状态',
    'customers.actions': '操作',
    'customers.vip': 'VIP',
    'customers.regular': '普通',
    'customers.new': '新客户',
    'customers.active': '活跃',
    'customers.inactive': '不活跃',
    'customers.blocked': '已屏蔽',
    'customers.viewProfile': '查看资料',
    'customers.sendEmail': '发送邮件',
    'customers.blockCustomer': '屏蔽��户',
    'customers.deleteCustomer': '删除客户',
    'customers.tier': '等级',
    'customers.location': '位置',
    'customers.joinDate': '加入日期',
    'customers.lastVisit': '最后访问',
    'customers.phone': '电话',
    'customers.filterStatus': '按状态筛选',
    'customers.filterTier': '按等级筛选',
    'customers.allTiers': '所有等级',
    'customers.selected': '已选择',
    'customers.bulkActions': '批量操��',
    
    // Vendor
    'vendor.title': '供应商',
    'vendor.subtitle': '管理您的供应商关系',
    'vendor.addVendor': '添加供应商',
    'vendor.reviewApplications': '审核申请',
    'vendor.review': '审核',
    'vendor.totalVendors': '总供应商数',
    'vendor.active': '活跃',
    'vendor.pending': '待审核',
    'vendor.pendingSubVendorsOnly': '{count} 个供应商账户为待处理状态',
    'vendor.pendingSubAppsOnly': '{count} 份申请待审核',
    'vendor.pendingSubBoth': '{vendorCount} 个供应商账户 · {appCount} 份申请',
    'vendor.inactive': '不活跃',
    'vendor.restrictedVendorStat': '已暂停 · 已封禁',
    'vendor.totalRevenue': '总收入',
    'vendor.totalProducts': '总产品数',
    'vendor.searchPlaceholder': '搜索供应商...',
    'vendor.name': '姓名',
    'vendor.email': '电子邮件',
    'vendor.products': '产品',
    'vendor.revenue': '收入',
    'vendor.commission': '佣金',
    'vendor.status': '状态',
    'vendor.joined': '加入日期',
    'vendor.actions': '操作',
    'vendor.viewProfile': '查看资料',
    'vendor.edit': '编辑',
    'vendor.sendEmail': '发送邮件',
    'vendor.suspend': '暂停',
    'vendor.delete': '删除',
    'vendor.deleteConfirm': '您确定要删除此供应商吗？',
    'vendor.deleteSuccess': '✅ 供应商删除成功！',
    'vendor.deleteError': '删除供应商失败',
    'vendor.bulkDeleteConfirm': '您确定要删除 {count} 个供应商吗？',
    'vendor.bulkDeleteSuccess': '✅ {count} 个供应商删除成功！',
    'vendor.bulkDeleteError': '删除供应商失败',
    'vendor.noResults': '未找到供应商',
    'vendor.filterStatus': '按状态筛选',
    'vendor.allStatus': '所有状态',
    'vendor.export': '导出',
    'vendor.suspended': '已暂停',
    'vendor.banned': '已封禁',
    
    // Blog Category
    'blogCategory.title': '博客分类',
    'blogCategory.subtitle': '组织您的博客内容',
    'blogCategory.addCategory': '添加分类',
    'blogCategory.totalCategories': '总分类数',
    'blogCategory.totalPosts': '总文章数',
    'blogCategory.searchPlaceholder': '搜索分类...',
    'blogCategory.category': '分类',
    'blogCategory.slug': '别名',
    'blogCategory.posts': '文章',
    'blogCategory.status': '状态',
    'blogCategory.created': '创建日期',
    'blogCategory.actions': '操作',
    'blogCategory.edit': '编辑',
    'blogCategory.delete': '删除',
    'blogCategory.addNewCategory': '添加新分类',
    'blogCategory.categoryName': '分类名称',
    'blogCategory.categoryNamePlaceholder': '例如：商业技巧',
    'blogCategory.categorySlug': '别名',
    'blogCategory.categorySlugPlaceholder': '例如：business-tips',
    'blogCategory.categoryDescription': '描述',
    'blogCategory.categoryDescriptionPlaceholder': '此分类的简要描述...',
    'blogCategory.parentCategory': '父分类',
    'blogCategory.none': '无',
    'blogCategory.cancel': '取消',
    'blogCategory.createCategory': '创建分类',
    'blogCategory.saveChanges': '保存更改',
    
    // Add Blog Post
    'addBlogPost.title': '创建新博客文章',
    'addBlogPost.editTitle': '编辑博客文章',
    'addBlogPost.back': '返回文章列表',
    'addBlogPost.saveDraft': '保存为草稿',
    'addBlogPost.publish': '发布',
    'addBlogPost.update': 'Update Post',
    'addBlogPost.basicInfo': 'Basic Information',
    'addBlogPost.postTitle': 'Post Title',
    'addBlogPost.postTitlePlaceholder': 'Enter an engaging title...',
    'addBlogPost.excerpt': 'Excerpt',
    'addBlogPost.excerptPlaceholder': 'Write a brief summary (shown in preview cards)...',
    'addBlogPost.content': 'Content',
    'addBlogPost.contentPlaceholder': 'Write your blog post content here...',
    'addBlogPost.formatting': 'Formatting',
    'addBlogPost.bold': 'Bold',
    'addBlogPost.italic': 'Italic',
    'addBlogPost.heading': 'Heading',
    'addBlogPost.bulletList': 'Bullet List',
    'addBlogPost.numberedList': 'Numbered List',
    'addBlogPost.quote': 'Quote',
    'addBlogPost.code': 'Code',
    'addBlogPost.link': 'Link',
    'addBlogPost.media': 'Media',
    'addBlogPost.coverImage': 'Cover Image',
    'addBlogPost.coverImageDesc': 'This image will be displayed as the post thumbnail',
    'addBlogPost.uploadImage': 'Upload Image',
    'addBlogPost.pasteUrl': 'Paste URL',
    'addBlogPost.imageUrlPlaceholder': 'Paste image URL...',
    'addBlogPost.addImage': 'Add Image',
    'addBlogPost.addToContent': 'Add to Content',
    'addBlogPost.insertImage': 'Insert Image',
    'addBlogPost.addVideo': 'Add Video',
    'addBlogPost.videoUrlPlaceholder': 'Paste video URL (YouTube, Vimeo, etc.)...',
    'addBlogPost.insertVideo': 'Insert Video',
    'addBlogPost.seoSettings': 'SEO Settings',
    'addBlogPost.metaDescription': 'Meta Description',
    'addBlogPost.metaDescriptionPlaceholder': 'Brief description for search engines (150-160 characters)...',
    'addBlogPost.tags': 'Tags',
    'addBlogPost.tagsDesc': 'Add tags to help readers find your content',
    'addBlogPost.addTagPlaceholder': 'Add a tag...',
    'addBlogPost.addTag': 'Add',
    'addBlogPost.publishSettings': 'Publishing Settings',
    'addBlogPost.status': 'Status',
    'addBlogPost.draft': 'Draft',
    'addBlogPost.published': 'Published',
    'addBlogPost.scheduled': 'Scheduled',
    'addBlogPost.category': 'Category',
    'addBlogPost.selectCategory': 'Select category',
    'addBlogPost.uncategorized': 'Uncategorized',
    'addBlogPost.author': 'Author',
    'addBlogPost.authorPlaceholder': 'Author name',
    'addBlogPost.publishDate': 'Publish Date',
    'addBlogPost.featured': 'Featured Post',
    'addBlogPost.featuredDesc': 'Show this post prominently on your blog',
    'addBlogPost.comments': 'Allow Comments',
    
    // Campaign Form
    'campaignForm.createTitle': 'Create Campaign',
    'campaignForm.editTitle': 'Edit Campaign',
    'campaignForm.back': 'Back',
    'campaignForm.saveDraft': 'Save Draft',
    'campaignForm.create': 'Create Campaign',
    'campaignForm.save': 'Save Changes',
    'campaignForm.basicInfo': 'Basic Information',
    'campaignForm.campaignName': 'Campaign Name',
    'campaignForm.campaignNamePlaceholder': 'e.g., Summer Sale 2026',
    'campaignForm.campaignType': 'Campaign Type',
    'campaignForm.discount': 'Discount/Coupon',
    'campaignForm.pushNotification': 'Push Notification',
    'campaignForm.seasonal': 'Seasonal Campaign',
    'campaignForm.discountSettings': 'Discount Settings',
    'campaignForm.discountCode': 'Discount Code',
    'campaignForm.discountCodePlaceholder': 'e.g., SUMMER2026',
    'campaignForm.discountType': 'Discount Type',
    'campaignForm.percentage': 'Percentage',
    'campaignForm.fixedAmount': 'Fixed Amount',
    'campaignForm.discountValue': 'Discount Value',
    'campaignForm.targetAudience': 'Target Audience',
    'campaignForm.allCustomers': 'All Customers',
    'campaignForm.newCustomers': 'New Customers',
    'campaignForm.vipCustomers': 'VIP Customers',
    'campaignForm.notificationSettings': 'Notification Settings',
    'campaignForm.notificationTitle': 'Notification Title',
    'campaignForm.notificationTitlePlaceholder': 'e.g., Flash Sale Alert! 🔥',
    'campaignForm.notificationMessage': 'Message',
    'campaignForm.notificationMessagePlaceholder': 'Write your notification message...',
    'campaignForm.sendImmediately': 'Send Immediately',
    'campaignForm.schedule': 'Schedule for Later',
    'campaignForm.scheduledDate': 'Scheduled Date & Time',
    
    // Auth Modal
    'auth.welcomeBack': 'Welcome back',
    'auth.signInContinue': 'Sign in to continue',
    'auth.createAccount': 'Create your account',
    'auth.getStarted': 'Get started with Migoo',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Enter your full name',
    'auth.phoneNumber': 'Phone Number',
    'auth.phoneNumberPlaceholder': '+95 9 XXX XXX XXX',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.orContinueWith': 'Or continue with',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.agreeToTerms': 'By signing up, you agree to our Terms of Service and Privacy Policy',
    
    // Auth - Login
    'auth.login.title': '欢迎回来',
    'auth.login.subtitle': '登录以管理您的 Migoo 平台',
    'auth.login.email': '电子邮箱',
    'auth.login.emailPlaceholder': 'owner@migoo.com',
    'auth.login.password': '密码',
    'auth.login.passwordPlaceholder': '输入您的密码',
    'auth.login.forgotPassword': '忘记密码？',
    'auth.login.signIn': '登录',
    'auth.login.signingIn': '登录中...',
    'auth.login.error': '登录失败。请检查您的凭据。',
    'auth.login.agree': '我同意条款和条件',
    'auth.login.agreeError': '您必须同意条款和条件才能继续。',
    'auth.login.rememberMe': '保持登录状态',
    'auth.login.rememberMeHint': '在此设备上保持登录',
    
    // Auth - Forgot Password
    'auth.forgotPassword.title': '重置密码',
    'auth.forgotPassword.subtitle': '选择您要重置密码的方式',
    'auth.forgotPassword.back': '返回登录',
    'auth.forgotPassword.viaEmail': '通过电子邮件',
    'auth.forgotPassword.viaSms': '通过短信',
    'auth.forgotPassword.emailLabel': '电子邮箱',
    'auth.forgotPassword.emailPlaceholder': 'owner@migoo.com',
    'auth.forgotPassword.emailHint': '我们将向此邮箱发送密码重置链接',
    'auth.forgotPassword.emailOtpHint': '我们将向此邮箱发送6位数验证码',
    'auth.forgotPassword.phoneLabel': '电话号码',
    'auth.forgotPassword.smsHint': '我们将向此号码发送OTP验证码',
    'auth.forgotPassword.sendResetLink': '发送重置链接',
    'auth.forgotPassword.sendOtp': '发送验证码',
    'auth.forgotPassword.sending': '发送中...',
    'auth.forgotPassword.error': '发送重置说明失败',
    'auth.forgotPassword.otpError': '验证码无效或已过期',
    'auth.forgotPassword.enterOtp': '输入验证码',
    'auth.forgotPassword.otpSentEmail': '我们已向您的邮箱发送6位数验证码',
    'auth.forgotPassword.otpSentPhone': '��们已向您的手机发送6���数验证码',
    'auth.forgotPassword.otpCode': '验证码',
    'auth.forgotPassword.otpHint': '输入您收到的6位数验证码',
    'auth.forgotPassword.verifyOtp': '验证',
    'auth.forgotPassword.verifying': '验证中...',
    'auth.forgotPassword.resendOtp': '重新发送验证码',
    'auth.forgotPassword.successTitle': '请检查您的收件箱！',
    'auth.forgotPassword.emailSent': '密码重置链接已发送！请检查您的邮箱。',
    'auth.forgotPassword.checkEmail': '我们已向您的邮箱发送密码重置链接。点击链接以重置您的密码。',
    'auth.forgotPassword.smsSent': '我们已向您的手机发送OTP验证码。输入验证码以重置您的密码。',
    'auth.forgotPassword.backToLogin': '返回登录',
    'auth.forgotPassword.sendReset': '发送重置链接',
    'auth.forgotPassword.setupWarning': '短信需要在Supabase中设置Twilio。请改用电子邮件以获得即时发送。',
    'auth.forgotPassword.emailRecommended': '电子邮件OTP已准备好使用！请检查您的收件箱以获取6位数代码（可能需要1-2分钟）。',
    
    // Auth - Reset Password
    'auth.resetPassword.title': '创建新密码',
    'auth.resetPassword.subtitle': '在下方输入您的新密码',
    'auth.resetPassword.newPassword': '新密码',
    'auth.resetPassword.passwordPlaceholder': '输入新密码',
    'auth.resetPassword.confirmPassword': '确认新密码',
    'auth.resetPassword.confirmPasswordPlaceholder': '重新输入新密码',
    'auth.resetPassword.passwordHint': '必须至少8个字符',
    'auth.resetPassword.update': '更新密码',
    'auth.resetPassword.updating': '更新中...',
    'auth.resetPassword.error': '重置密码失败',
    'auth.resetPassword.passwordMismatch': '密码不匹配',
    'auth.resetPassword.passwordTooShort': '密码必须至少8个字符',
    'auth.resetPassword.successTitle': '密码已更新！',
    'auth.resetPassword.successMessage': '您的密码已成功重置。',
    'auth.resetPassword.redirecting': '正在重定向到登录...',
    
    // Auth - Setup
    'auth.setup.title': '设置超级管理员',
    'auth.setup.subtitle': '创建您的所有者账户（仅限一次）',
    'auth.setup.name': '全名',
    'auth.setup.namePlaceholder': '您的姓名',
    'auth.setup.email': '电子邮箱',
    'auth.setup.emailPlaceholder': 'owner@migoo.com',
    'auth.setup.phone': '电话号码（可选）',
    'auth.setup.password': '密码',
    'auth.setup.passwordPlaceholder': '创建一个强密码',
    'auth.setup.confirmPassword': '确认密码',
    'auth.setup.confirmPasswordPlaceholder': '重新输入您的密码',
    'auth.setup.create': '创建超级管理员账户',
    'auth.setup.creating': '正在创建账户...',
    'auth.setup.error': '创建账户失败。请重试。',
    'auth.setup.passwordMismatch': '密码不匹配',
    'auth.setup.passwordTooShort': '密码必须至少8个字符',
    'auth.setup.info': '此页面在首次使用后将自毁',
    'auth.setup.successTitle': '账户创建成功！',
    'auth.setup.successMessage': '您的超级管理员账户已创建。您现在可以登录。',
    'auth.setup.goToLogin': '前往登录',
    'auth.setup.footerPrompt': '已有账户？',
    'auth.setup.footerSignIn': '登录',
    
    // Auth - Change Password
    'auth.changePassword.title': '更改密码',
    'auth.changePassword.subtitle': '您必须更改临时密码',
    'auth.changePassword.newPassword': '新密码',
    'auth.changePassword.passwordPlaceholder': '输入新密码',
    'auth.changePassword.confirmPassword': '确认新密码',
    'auth.changePassword.confirmPasswordPlaceholder': '重新输入新密码',
    'auth.changePassword.passwordHint': '必须至少8个字符',
    'auth.changePassword.update': '更新密码',
    'auth.changePassword.updating': '更新中...',
    'auth.changePassword.error': '更新密码失败',
    'auth.changePassword.passwordMismatch': '密码不匹配',
    'auth.changePassword.passwordTooShort': '密码必须至少8个字符',
    
    // User Management
    'userManagement.title': '用户管理',
    'userManagement.subtitle': '创建和管理用户账户',
    'userManagement.addUser': '添加用户',
    'userManagement.totalUsers': '总用户数',
    'userManagement.name': '姓名',
    'userManagement.email': '电子邮箱',
    'userManagement.phone': '电话',
    'userManagement.role': '角色',
    'userManagement.actions': '操作',
    'userManagement.edit': '编辑',
    'userManagement.delete': '删除',
    'userManagement.resetPassword': '重置密码',
    'userManagement.confirmDelete': '您确定要删除此用户吗？',
    
    // User Form
    'userForm.addTitle': '添加新用户',
    'userForm.editTitle': '编辑用户',
    'userForm.name': '全名',
    'userForm.namePlaceholder': '张三',
    'userForm.email': '电子邮箱',
    'userForm.emailPlaceholder': 'john@example.com',
    'userForm.phone': '电话号码',
    'userForm.phonePlaceholder': '+95 9 XXX XXX XXX',
    'userForm.password': '临时密码',
    'userForm.passwordPlaceholder': '将自动生成',
    'userForm.role': '用户角色',
    'userForm.selectRole': '选择角色',
    'userForm.store': '分配商店（供应商管理员/协作者）',
    'userForm.selectStore': '选择商店',
    'userForm.cancel': '取消',
    'userForm.save': '保存用户',
    'userForm.create': '创建用户',
    'userForm.creating': '创建中...',
    'userForm.saving': '保存中...',
    
    // Roles
    'role.superAdmin': '超级管理员',
    'role.superAdmin.desc': '对所有供应商和平台设置的完全访问权限',
    'role.vendorAdmin': '供应商管理员',
    'role.vendorAdmin.desc': '管理自己的商店、产品和订单',
    'role.collaborator': '协作者',
    'role.collaborator.desc': '有限访问权限以帮助管理供应商商店',
    
    // Inventory Adjust Dialog
    'inventory.dialog.adjust.title': '调整库存',
    'inventory.dialog.adjust.description': '更新库存数量和SKU',
    'inventory.dialog.currentStock': '当前库存',
    'inventory.dialog.available': '可用',
    'inventory.dialog.adjustment': '调整数量',
    'inventory.dialog.adjustmentPlaceholder': '输入数量（减少用 -）',
    'inventory.dialog.adjustmentHint': '使用正数添加库存，负数减少',
    'inventory.dialog.preview': '预览：',
    'inventory.dialog.newStock': '新库存：',
    'inventory.dialog.sku': 'SKU',
    'inventory.dialog.skuPlaceholder': '输入SKU',
    'inventory.dialog.skuHint': '如需要可更新SKU号码',
    'inventory.dialog.cancel': '取消',
    'inventory.dialog.save': '保存更改',
    'inventory.dialog.saving': '保存中...',
    
    // Inventory Bulk Adjust Dialog
    'inventory.dialog.bulk.title': '批量调整库存',
    'inventory.dialog.bulk.description': '调整库存��平',
    'inventory.dialog.bulk.selectedItems': '已选项目：',
    'inventory.dialog.bulk.current': '当前：',
    'inventory.dialog.bulk.adjustmentHint': '此调整将应用于所有',
    'inventory.dialog.bulk.selectedItemsHint': '已选项目',
    'inventory.dialog.bulk.previewChanges': '预览更改：',
    'inventory.dialog.bulk.andMore': '...还有',
    'inventory.dialog.bulk.moreItems': '个项目',
    'inventory.dialog.bulk.applyToAll': '应用于所有已选',
    
    // Inventory Success/Error Messages
    'inventory.success.adjusted': '库存调整成功',
    'inventory.success.bulkAdjusted': '批量库存调整完成',
    'inventory.error.adjust': '调整库存失败',
    'inventory.error.load': '加载库存数据失败',
    'inventory.error.invalidQty': '请输入有效数量',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load saved language
    try {
      const saved = localStorage.getItem('migoo-language');
      if (saved === 'en' || saved === 'zh') {
        setLanguageState(saved);
      }
    } catch (error) {
      console.error('Failed to load language:', error);
    }
  }, []);

  useEffect(() => {
    // Save language
    try {
      localStorage.setItem('migoo-language', language);
    } catch (error) {
      console.error('Failed to save language:', error);
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}